# Generated by Django 5.2 on 2025-04-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='documents',
        ),
    ]
